Repository inspirehep/hepcrawl, pull requests merged in 2018-02, with the labels that each got.

#224 travis: deploy only on one of the test suites
  .travis.yml
Labels: Review: Ready for Integration

#225 utils.strict_kwargs: whitelist crawler_settings param
  hepcrawl/utils.py
  tests/unit/test_utils.py
Labels: Review: WIP

#217 oaipmh_spider: allow harvesting single records
  hepcrawl/spiders/arxiv_spider.py
  hepcrawl/spiders/common/oaipmh_spider.py
  tests/functional/arxiv/fixtures/arxiv_expected_single.json
  tests/functional/arxiv/fixtures/http_server/conf/proxy.conf
  tests/functional/arxiv/fixtures/http_server/records/arxiv-single.xml
  tests/functional/arxiv/test_arxiv.py
Labels: Review: WIP

#227 utils: use passive FTP by default
  .travis.yml
  docker-compose.test.yml
  hepcrawl/utils.py
Labels: Review: WIP

#228 utils: remove extra get_first
  hepcrawl/utils.py
Labels: Review: WIP

#229 pipelines: return a crawl_result object instead of just the record
  hepcrawl/api.py
  hepcrawl/pipelines.py
  hepcrawl/spiders/desy_spider.py
  hepcrawl/testlib/scrapyd_coverage_runner.py
  hepcrawl/tohep.py
  hepcrawl/utils.py
  setup.py
  tests/functional/arxiv/test_arxiv.py
  tests/functional/cds/test_cds.py
  tests/functional/desy/test_desy.py
  tests/functional/pos/test_pos.py
  tests/functional/wsp/test_wsp.py
  tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json
  tests/unit/test_arxiv_all.py
  tests/unit/test_arxiv_single.py
  tests/unit/test_desy.py
  tests/unit/test_pipelines.py
  tests/unit/test_pos.py
  tests/unit/test_world_scientific.py
Labels: Review: Ready for Review

#230 global: replace get_nested util with get_value
  hepcrawl/spiders/aps_spider.py
  hepcrawl/utils.py
  tests/unit/test_utils.py
Labels: Review: WIP

#232 settings: reorder middlewares
  hepcrawl/settings.py
Labels: Review: WIP
